trigger:
- none

pool:
  name: evaluation

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'aws --version'

# - script: |
#     if aws cloudformation describe-stacks --stack-name test >/dev/null 2>&1; then
#       echo "Stack already exists, skipping deployment."
#     else
#       aws cloudformation deploy --template-file cftemplate --stack-name test --parameter-overrides KeyName=trail
#     fi
#   displayName: 'Deploy CloudFormation Stack'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      if aws cloudformation describe-stacks --stack-name test >/dev/null 2>&1; then
            echo "Stack already exists, skipping deployment."
          else
            aws cloudformation deploy --template-file cftemplate --stack-name test --parameter-overrides KeyName=trail
          fi